language: android
before_install:
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
android:
  components:
    - build-tools-26.0.1
    - android-26
  licenses:
    - android-sdk-license-.+
    - '.+'
install:
  - true
script:
  - ./gradlew testDevDebugUnitTest assembleDebug assembleAndroidTest
after_success:
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-127.0.0-linux-x86_64.tar.gz
  - tar xf google-cloud-sdk-127.0.0-linux-x86_64.tar.gz
  - echo "y" | ./google-cloud-sdk/bin/gcloud components update beta
  - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file secret.json
  - ./google-cloud-sdk/bin/gcloud beta test android run --async --type instrumentation --app app/build/outputs/apk/automation/debug/app-automation-debug.apk --test app/build/outputs/apk/androidTest/automation/debug/app-automation-debug-androidTest.apk --device-ids athene_f  --os-version-ids 23 --locales en_US --orientations portrait --project pkmng-ff0d2
deploy:
  provider: releases
  api_key: "AbfjxPRkJd1Nng+NSIBlZx3w+1in3neNEv7/+PHJcu7CFtfNBpxlvxxDgcSHnJwNIzlxgAAP5qdpMrINWZeoekCwUPnRspyxcZg3ldG6sCLWhBAWkTH/6ydsi6WfseG9fZZWgRkYMarRbGL/IQ+3zhTa5C42purHGeZFz1hnRZB7uuTRci12qLsV8u8ilSRwTxI0gzfs43pAjZE3nbH5V+dTvRwOEHhnAzhKcwAaZQCDDJ0AdqfZ6TFvO39Zs/CZGO+LzsNYiBoe5Zi2xLyv4F78zsBix6rWc94Hxd4RZfzVnLIhBnFe1LFDQ33wCZ/etkrCkO2c6WKfAfZyD5W2xtwndTf9Qu+6iD1EhvdwlmKX9OJD282TdfjxoNGF9HRpnnKiVzM6yqVEHGJq9LPqqKCoX8UUzGwvd4jIIHZyCsBUFS2BHW3Wx9qtGLIPRi5IG7JayeMnMqAVcbI7oXa8JGKheXMrQuMmSMngfF9lg8mmZU0wcjwU6r41hEOE/dv024PvHA1tUFM0BbnsSx/rm1WUy1S5jZ4UfTYD5XecLIdSByvdiG9jkToeTVaxBDWR8RrE3OHWuFpqqlU2E+83w5t/PEm/2I300+n1nv9J56dDrPQJ77BKeuWqsodC1wr46t9Dzf4+MM7+6oqm+BVPR7dqgMwnS9wcPj9EzaGxucQ="
  file: "app/build/outputs/apk/dev/debug/app-dev-debug.apk"
  skip_cleanup: true
  on:
    branch: master
    repo: AlvaroChambi/PKMNG