language: android
before_install:
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
android:
  components:
    - build-tools-26.0.1
    - android-26
  licenses:
    - android-sdk-license-.+
    - '.+'
install:
  - true
script:
  - ./gradlew testDevDebugUnitTest assembleDevDebug --scan -s assembleAndroidTest
after_success:
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-127.0.0-linux-x86_64.tar.gz
  - tar xf google-cloud-sdk-127.0.0-linux-x86_64.tar.gz
  - echo "y" | ./google-cloud-sdk/bin/gcloud components update beta
  - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file secret.json
  - ./google-cloud-sdk/bin/gcloud beta test android run --async --type instrumentation --app app/build/outputs/apk/automation/debug/app-automation-debug.apk --test app/build/outputs/apk/androidTest/automation/debug/app-automation-debug-androidTest.apk --device-ids athene_f  --os-version-ids 23 --locales en_US --orientations portrait --project pkmng-ff0d2
deploy:
  provider: releases
  api_key:
    secure: "xx3Ggh3jMEU7KtJSXU9F54uol/cNP0tpLTPheS00OybYJUo5yHcS1TIbDnTgT+Ijaj/AXO5JtuZwCxyfRpZzACOaAikBSeBSvCQJL2752Q1nqxrMxaYq7W2eOMvvehZKb3Z1LqvwdcTKjJXaTGL+1ihZBNypSkQ0lA7lDhEIrtQhYMGw46AMRGzU8WbtYDKbycso8lCHIZpjPK9Y4rq1jq3TN8V2p6pdTpIUGeF6S3nDWYKzJFi6OVQxi1ZG85+iKXebovBHwlvXXeGrZaRo1lc7gXeLhmliRibNcyg0eregAj7b1xmZzngCNnJKFchA+u2Ea7R/rDwjBsh8eq672W1quTAxnGBAIWz8ifA/AB0Xf1i6PnIz69VOz0tdnXST96Out6FFXQeMwsDegEQ4RuP4z4wuuZcaTZ5nqIIAPuhuEqkUFMJhVIY9ijhAtZXLpJ0Q45+XGO3mtys661Gw9J8uuplA4TSI5W7yPAaS+zywX5/Dcjqj997NFVs+8OOYJcDxDkkNb5wqmj+IYS2Y5L3N++vopN9ZnR87WJEeC3MJ1HX/DCt7w9FEL1dV6Tx40B95gYbpgKLvYom/9cVrC2RVHbvzBI5Sv+OvfksIvU2GBtlffri92m+HUe/m5Z+tJ3mmBai/atM3z9WhN9HxqY6M+LvEQV2h+ls67F7vnk8="
  file: "app/build/outputs/apk/dev/debug/app-dev-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: AlvaroChambi/PKMNG